name = "enumerate"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Joel Reymont"]
maintainers = ["Joel Reymont <joelr1@gmail.com>"]
maintainers-logins = ["joelreymont"]

executables = ["enumerate"]
[[depends-on]]
libusb_ada = "~0.1.0-dev"
[[pins]]
libusb_ada = { path='..' }
