name = "libusb_ada"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Joel Reymont"]
maintainers = ["Joel Reymont <joelr1@gmail.com>"]
maintainers-logins = ["joelreymont"]
[[depends-on]]
libusb = "^1.0.26"
[[depends-on]]
gnatcoll = "^23.0.0"
